### ISSUE TITLE
Account for tree shaking

### ISSUE THREAD

**Issue by FND** [doesdev/rollup-analyzer#3]
Thanks a lot for this; we're considering using it for [faucet-pipeline](http://www.faucet-pipeline.org).

However, as far as I can tell, tree shaking is not being taken into account, which makes results potentially misleading (see https://github.com/faucet-pipeline/faucet-pipeline-js/pull/39 for details). Is this something that could be fixed or does Rollup only expose the original code (via `bundle.modules`), before it's been processed?

**Comment by doesdev** [comment]
Thanks for the report, I'll take a look tomorrow and see what I can figure out.

**Comment by doesdev** [comment]
Confirmed it isn't being accounted for and added a (failing) test for it. Now to figure what rollup exposes to get it working.

**Comment by doesdev** [comment]
Sorry for the delay, should have gotten a PR in earlier but the Rollup team has worked in enhancements that allow for this. Currently it is only implemented in the [`rollup-analyzer-plugin`](https://github.com/doesdev/rollup-analyzer-plugin) module. I'm still working on a 2.0 version of the full module that will include this, but the plugin can be used now. 

The 2.0.0 release will also include info on original code vs. treeshaken sizes / reduction percentages and a few other additional pieces of data.

**Comment by FND** [comment]
No worries; we're grateful for your efforts! I'll look into this soon(ish) and will report back.

**Comment by doesdev** [comment]
So, after spending time reworking around the updated data rollup exposes via plugin hooks I realized that this module itself isn't very useful. The plugin is, but it is also not in line with rollup's standards / recommendations for plugins, primarily the plugin name itself.

For those reasons I'm going to be reworking this module to refer people to the updated plugin. I will see if I can get NPM to point the old plugin to the new. 

All that to say, the new plugin prioritizes treeshaking, breaking out what percentages were trimmed and also contains a number of other enhancements over this.

Here's the link to the new plugin:
[rollup-plugin-analyzer](https://github.com/doesdev/rollup-plugin-analyzer)

I'm going to close this as that plguin should definitely take care of the concerns here, but if you do have any other issues come up with it let me know over there.

**Comment by FND** [comment]
I've now had a chance to try this, and it appears to work pretty well - thank you!

We still have to work out a few details - mostly about when to emit the full report; you probably don't want this whenever the bundle is recompiled in watch mode - but I expect it'll land in faucet soon.
